### PR TITLE
refactoring fresh generators

### PR DESCRIPTION
**Pull request by madvorak**

### CODE REVIEW

**Comment by teorth** [comment]
@b-reinke Are there any interactions between this PR and your current formalizations that one should be aware of?

**Comment by b-reinke** [comment]
No, I am working on 3308, but using the proof that is not translation invariant

**Comment by b-reinke** [comment]
There is also 1516 that hasn't been refactored to depend on `FreshGenerator.lean` yet, but probably it would be nicer to do this from scratch, also getting rid of the dependence on `Finmap`

**Comment by madvorak** [comment]
I am happy to close it now and refactor it later. What is easier for you?

**Comment by b-reinke** [comment]
For me now would be ok.

**Comment by teorth** [comment]
@b-reinke To clarify, by "now would be ok" you mean that you have no objection with the current PR being merged?

**Comment by b-reinke** [comment]
Yes, from my perspective it can be merged

**Pull request merged**
