### PR TITLE
Export equations

### PR DESCRIPTION
**Pull request by 0art0**
Exports the equations defined in `Equations.lean` and `AllEquations.lean` to a JSON file `data/magma_equations.json`.

Depends on PR #427.

### CODE REVIEW

**Comment by 0art0** [comment]
I was also considering adding the generated JSON file to the PR, but I haven't done that yet since it's a sizeable file.

**Comment by pitmonticone** [comment]
Thank you @0art0! Please make sure the project builds correctly by locally running `scripts/run_before_push.sh`.

**Comment by pitmonticone** [comment]
Thank you @0art0! Please make sure the project builds correctly by locally running `scripts/run_before_push.sh`.

**Comment by 0art0** [comment]
awaiting-review

**Comment by pitmonticone** [comment]
I'm inclined to merge both PRs (#427 and #429) because they look fine to me (even if the branch of #429 seem to have been created from the branch of #427 which isn't considered best practice), but I may be missing something.

See discussion here https://leanprover.zulipchat.com/#narrow/stream/458659-Equational/topic/Do.20we.20need.20to.20build.20EquationalSearch.20files.3F/near/475682423

**Comment by pitmonticone** [comment]
Thanks again @0art0

**Pull request merged**
