### PR TITLE
FiniteMagmaExplorer: integrate into project repo (#332)

### LINKED ISSUE #332: FRONTEND: A web page that takes in a finite magma (in some standardized format), and returns the equations obeyed or not obeyed by this magma.
If this submitted magma generates new anti-implications, instructions would be given on how to submit it as a PR.  (I assume permitting direct submission to the repository would be a security risk, and possibly not even technically feasible even with admin privileges.)

The web page could provide some sample finite magmas as examples to illustrate the tool.

The equations listed can be linked to their corresponding pages on https://teorth.github.io/equational_theories/implications/

### PR DESCRIPTION
**Pull request by zaklogician**
The Finite Magma Explorer is a new tool that lets you input the operator table of any finite magma, and returns which equations are satisfied by the given magma.
    
Previously, Finite Magma Explorer was developed in an external repository. This PR integrates Finite Magma Explorer into the main project repository to maximize compatibility, maintainability, and ensure integrated future development, as discussed in #332.

**What this PR does:**

1. Creates a `tools/fme` directory, where the Finite Magma Explorer source code lives. Includes a pre-built copy of the website in `dist/` (see discussion in #332) which CI can use to build the website, and the Elm sources in `src/`. Includes build instructions to get from the former to the latter.

2. Updates the main project README with a link to the tool, and adds a button to the website with the same effect.

3. Updates the documentation of `All4x4Tables` to reference the Finite Magma Explorer.

4. The main script intended for CI use is `tools/fme/generate_fme_website.sh`. It combines `dist/` with the latest Lean-generated dataset, and puts the result into `home_page/fme`.

**What needs to be done**

Since this adds public-facing features and makes changes to existing ones, it needs a review and some testing. The CI scripts will have to be integrated as well (I don't think I can do this, but I'm happy to assist).

Closes #332

### CODE REVIEW

**Comment by zaklogician** [comment]
(NB I'll need assistance from a repo owner or collaborator to progress this, since I can't test or work on the CI myself.)

**Comment by pitmonticone** [comment]
Hi @zaklogician, I can assist on this one.

**Comment by zaklogician** [comment]
Thanks!

**Comment by pitmonticone** [comment]
We will collaborate on this PR branch. I'll write the relevant CI step, but I need to understanding everything that is going on first. 

In particular, I need to understand conceptual workflow.

**Comment by zaklogician** [comment]
Okay, here's the deal:

1. The tool itself is written in Elm and JavaScript. The elm parts are compiled using `elm build` into `elm.js`, which is the app's main entry point, included from `index.html`.

2. We probably don't want to have a CI dependency on Elm (IIRC there's no pre-made package for this, so one has to obtain the compiler and get it into a runnable state manually from Github Actions).

3. So, I included a copy of the app `dist/` which has the elm parts pre-compiled. However, this does not include the data files (`unknown.json` and the version string for now) that come from the Lean proofs.

4. The CI should assemble the Finite Magma Explorere website in `home_page` by taking the stuff from `dist/`, baking in the version string, and supplying the Lean-generated data files.


That's my imagined workflow. Most of the contents of the `dist/` directory are probably superfluous in that you could source `elm.js` from dist and everything else directly from `src/`, and copy them into `home_page/fme`. I just thought it's simpler to have everything in one place.

Does this make sense?

**Comment by pitmonticone** [comment]
Ok, I have been able to serve Jekyll locally

Screenshot 2024-10-09 at 17 58 21
Screenshot 2024-10-09 at 17 58 26

**Review by pitmonticone — APPROVED** [review]

**Pull request merged**
