### PR TITLE
Auto-generated proofs for all laws trivially implying Eq2 (singleton) and Eq46 (constant)

### PR DESCRIPTION
**Pull request by amirlb**
This is done with a two large files, not with any kind of introspection on equation structure.

815 theorems are included for singletons and 85 for constant laws.

### CODE REVIEW

**Comment by teorth** [comment]
Can the code be refactored using the new AllEquations.lean?

**Comment by amirlb** [comment]
> Can the code be refactored using the new AllEquations.lean? I guess one should still record the list of constant and singleton equations somewhere, but not necessarily as a redundant list of defs

Done

**Comment by teorth** [comment]
Congrats, this is the first approved automated contribution to the implication graph!  I've announced it on the front page and also made a blueprint chapter (should appear shortly as chapter 6).  If you could update that chapter to describe the process to generate the contributions when you have a chance, that would be great.

**Comment by Command-Master** [comment]
@amirlb Could you please also PR the code used to produce these files?

**Comment by amirlb** [comment]
> @amirlb Could you please also PR the code used to produce these files?

Where would be an appropriate place to put it? These files are still in the main `Generated/` directory, should I move them to a subdirectory and add a generating script there?

**Pull request merged**
