### PR TITLE
[TEST] Propose PR Workflow

### LINKED ISSUE #63: [TEST] Claim, Disclaim and Link

### PR DESCRIPTION
**Pull request by pitmonticone**
Closes #63

### CODE REVIEW

**Comment by pitmonticone** [comment]
propose PR #63

**Comment by pitmonticone** [comment]
propose PR #63

**Comment by pitmonticone** [comment]
propose PR #63

**Comment by Shreyas4991** [comment]
We want the PR propose comment to be made on the issue

**Pull request closed without merging**
