### PR TITLE
 Show there is some implication which is only falsified in an infinite magma

### PR DESCRIPTION
**Pull request by Command-Master**
I'm not sure I edited the blueprint correctly

### CODE REVIEW

**Comment by teorth** [comment]
Looks good to me.  Only minor comments:

- One should add a \leanok to the proof as well as to the theorem, since you not only formalized the statements in Lean, but also provided proofs.
- Technically we are supposed to enclose each separate Lean contribution in their own namespace to avoid collisions, though in this case this is unlikely since we don't expect `EquationKis` to show up elsewhere.  (Though we could add it as Equation #4695, I guess, since it has some interest...)

**Comment by teorth** [comment]
Ah, once you put the Lean implications in a namespace you have to adjust the blueprint \lean{} references accordingly.  I got caught out by this also.  I'll update CONTRIBUTING.md to warn about this.

**Comment by Command-Master** [comment]
Could you expand on this? I was unable to resolve this without adding `import equational_theories.InfModel` to `equational_theories.lean`.

**Comment by teorth** [comment]
Oh, right, you should do that also.

**Pull request merged**
