### PR TITLE
add automatically generated proof of 14 implies 29

### LINKED ISSUE #120: SUBGRAPH: Show that 14 implies 29
This is the dual of the existing implication that 29 implies 14, and should be easy to add.  When done, one can update the `\lean{}` tag of `Theorem \ref{29_equiv_14}` in https://github.com/teorth/equational_theories/blob/main/blueprint/src/chapter/implications.tex , and also add a \leanok to the proof to finish it off.

### PR DESCRIPTION
**Pull request by shetzl**
null

Closes #120

### CODE REVIEW

**Review by madvorak — COMMENTED** [review]
just minor remarks about aesthetics

**Comment by pitmonticone** [comment]
Thank you @madvorak for your review, but at this stage we don't need these kinds of refinements. 

I'll clean and golf the Subgraph file every night (few nights).

**Comment by shetzl** [comment]
I will adapt the export code to get rid of these aesthetic problems. I should be able to commit an improved version tomorrow.

**Comment by teorth** [comment]
My view is Subgraph.lean is part of the human-curated project space, and so aethestic improvements to autogenerated proofs are completely welcome here.  In contrast, the Generated folder is for the 100% computer generated results, and human cleanup should ideally be avoided in that folder (but maybe some human-written files derived from a generated file can also be created, but outside of the Generated folder).  I'll update the CONTRIBUTING.md file to reflect this.

**Comment by pitmonticone** [comment]
Ok great. Thanks @shetzl and @madvorak

**Comment by pitmonticone** [comment]
Thanks @shetzl! Merged.

**Review by pitmonticone — APPROVED** [review]

**Comment by pitmonticone** [comment]
Thanks, merged.

**Pull request merged**
