### PR TITLE
Obelix =!=> Asterix, formal proof

### LINKED ISSUE #543: ASTERIX: Refute 1491 -> 65 ("Obelix" -> "Asterix")
A sketch of a construction is provided [here](https://leanprover.zulipchat.com/#narrow/stream/458659-Equational/topic/Oberlix.3A.20joining.20two.20approaches).

The task involves:
* Writing up the proof in the blueprint (presumably in the "Asterix" chapter);
* Stating and formalizing the proof in the `ManuallyProved` folder;
* Updating `ManuallyProved.lean` afterwards;
* Adding `\lean` and `\leanok` tags to the blueprint proof when done.

One could also claim just the first stage of this project if desired, in which case a new task will be issued for formalizing the blueprint.

### PR DESCRIPTION
**Pull request by Timeroot**
Working on #543. Still a draft! :) 

Closes #543

### CODE REVIEW

**Comment by pitmonticone** [comment]
Thank you @Timeroot for your contribution! 

Could you please fix the merge conflicts?

**Comment by Timeroot** [comment]
I will! It's not 100% done yet (I would like to finish the Lean proof, which I want to say is < 1 day of work left), I definitely will fix the merge conflicts once that's ready.

**Comment by pitmonticone** [comment]
> (I interpreted Shreyas's comment as saying I should 'propose' it now even though it's not done yet, if that was a misreading I apologize)

You interpreted it correctly. Feel free to propose this PR in the related issue.

**Comment by teorth** [comment]
"Obelisk" shoud be "Obelix" in the lean import files.  

Also, if you would like to update the blueprint to make LaTeX version of the proof (in the Asterix chapter, presumably) with \lean and \leanok tags, that would be great.  The proof can simply link to the Zulip discussion or pdf version of the proof if you are following that proof closely, but if you have any interesting deviations from that proof to report, that can also be mentioned there.

**Comment by Timeroot** [comment]
Haha, yeah not sure where "Obelisk" snuck into my head there. :)
I'll fix that -- the LaTeX is a bit outdated (it describes a "bifurcation tree" strategy that turned out not to work), so I'm going to fix that up to be correct tonight. And fix the merge conflict.

**Comment by Timeroot** [comment]
Alright, it's actually ready to merge now.

**Comment by teorth** [comment]
There's a blueprint build error: ! LaTeX Error: \begin{definition} on input line 212 ended by \end{document}.

You can try compiling print.tex locally, or using the `push_before_run` script, before uploading, though one way or another we should get this build to work...

**Comment by Timeroot** [comment]
I've had trouble getting blueprint to install (on a Mac, graphviz errors) so I was hoping I could write the LaTeX 'blind' and it would at least compile. Turns out my shooting accuracy for that is lower than expected. Think it's okay now though

**Pull request merged**
