### PR TITLE
split AllEquations into pieces for more parallelism

### PR DESCRIPTION
**Pull request by digama0**
While more can be done to improve the performance of the `equation` command, one thing that helps a lot is to make an embarrassingly-parallel task more parallel in practice by splitting it into separate files. The `Equation` files have also been moved into a common folder.

### CODE REVIEW

**Comment by carlini** [comment]
This might break some of the scripts that load equation data from this file. Ideally they wouldn't be doing that in the first place and should read from a separate python-friendly file. If things don't build for this reason I can try to to fix things.

**Comment by digama0** [comment]
Can you point me to the code that does this?

**Comment by carlini** [comment]
There are several I'm aware of:

https://github.com/teorth/equational_theories/blob/c27789ec7ea82c2d870080bf8c5bc0ff3af12a51/scripts/generate_graphiti_data.rb#L16

https://github.com/teorth/equational_theories/blob/c27789ec7ea82c2d870080bf8c5bc0ff3af12a51/scripts/explore_magma.py#L13

https://github.com/teorth/equational_theories/blob/c27789ec7ea82c2d870080bf8c5bc0ff3af12a51/scripts/find_dual.py#L169

https://github.com/teorth/equational_theories/blob/c27789ec7ea82c2d870080bf8c5bc0ff3af12a51/scripts/generate_equation_implication_js.py#L109

**Comment by Shreyas4991** [comment]
@digama0 : A lot of the automated diagram generating python and ruby scripts assume the existence of AllEquations.lean because this structure was agreed on near the beginning of the project. They read this file as a textfile. This isn't super ideal and maybe we should have written an export script in lean that exports the equations of "AllEquations.lean" into json. But fixing this now will be non-trivial.

**Comment by teorth** [comment]
This is what #142 is supposed to do.  Perhaps #427 can be adapted to create such a JSON, which all other tools then draw from?  Then if we ever refactor the equation lean files again then one just has to change the one export tool.

**Comment by carlini** [comment]
(I'd be happy to help rewrite the scripts to load from an appropriate json data file as appropriate.)

**Comment by Shreyas4991** [comment]
The [script that generated them] appears deterministic, so in principle, the same script can be modified to output the json file. However the script writers must then use this json file.

**Comment by vlad902** [comment]
I can update the ruby code when I'm back at the computer later today.

**Comment by digama0** [comment]
Note: the current state is that all scripts have been fixed, although I don't know how to use them all so they are only lightly tested.

**Comment by vlad902** [comment]
> Note: the current state is that all scripts have been fixed, although I don't know how to use them all so they are only lightly tested.

Ah, apologies for the confusion.

**Pull request merged**
