### PR TITLE
Update scripts/process_implications.py: use Lean parser, output irreducible implications

### PR DESCRIPTION
**Pull request by amirlb**
Update scripts/process_implications.py: to process the parsed implications JSON, and figure out the irreducible implications

### CODE REVIEW

**Comment by vlad902** [comment]
Running this gave me `All implications: 310354` while my own output is millions higher, am I misunderstanding the output or is that the size of the entire closure?

**Comment by vlad902** [comment]
```
lake exe extract_implications | ruby -rjson -e 'JSON.parse($stdin.read)["implications"].each { |s| puts s["lhs"][8,10] + "," + s["rhs"][8,10] }' | sort -u > /tmp/imp.csv
ruby scripts/transitive_closure.rb  /tmp/imp.csv | wc -l
```

Gives me 4.5 million, but I would totally believe the error is in `scripts/transitive_closure.rb`

**Comment by amirlb** [comment]
The figure 310354 is after reducing to the 3557 equivalence classes, without the internal implications in each class and with a single implication between every two related classes. That's probably the source of the difference.

**Comment by teorth** [comment]
Would it be possible to update the README.md to give links to this data and script, possibly with some warning that the data set is provisional and not guaranteed to be 100% accurate yet?  Having a easily accessible initial data set of implications, even if slightly off from the actual truth, may allow a lot of more data analysis / data visualization oriented people to be able to make some interesting contributions and insights.  (One can also think about adding a chapter to the blueprint to give a longer description of the methodology.)

**Comment by vlad902** [comment]
> The figure 310354 is after reducing to the 3557 equivalence classes, without the internal implications in each class and with a single implication between every two related classes. That's probably the source of the difference.

Ah, that makes sense. Given that there's two different graphs to be considering here, pre- and post-condensation, it's probably good to be explicit about it. I'd maybe say 'condensed implications' or something else you find more descriptive to make it clear to others who may be confused like me.

**Pull request merged**
