### PR TITLE
Extract implications: unknowns subcommands --duality flag

### LINKED ISSUE #397: FRONTEND: Add a script that filters unknown implications up to duality

### PR DESCRIPTION
**Pull request by amirlb**
Also add the current results, and correct the data of yesterday's files

Closes #397

### CODE REVIEW

**Comment by pitmonticone** [comment]
Thanks a lot! 

Is this PR ready to be merged or are you still working on it? 

If it's ready to be merged, please write `awaiting-review`.

**Comment by amirlb** [comment]
awaiting-review

**Comment by amirlb** [comment]
Thanks, I totally forgot about this step

**Comment by pitmonticone** [comment]
Thank you @amirlb. 

I merged `main`. I will for the CI and then I'll merge.

**Pull request merged**
