### PR TITLE
Add more bruteforced implications

### PR DESCRIPTION
**Pull request by vlad902**
This change introduces some more simple bruteforced implications. By my calculation, this change increases the transitive closure size from 4.5m to 4.75m.

### CODE REVIEW

**Comment by teorth** [comment]
Can you update the top-level README.md to report these improvements?  Also if you can update the blueprint to report on methodology and results that would also be great.

**Comment by vlad902** [comment]
> Can you update the top-level README.md to report these improvements? Also if you can update the blueprint to report on methodology and results that would also be great.

Done! Thanks for the reminder on the blueprint.

**Comment by teorth** [comment]
I think I may have caused a conflict with README.md by moving some stuff around.  Could you align your commit with the new version, then this PR can be merged.

**Comment by vlad902** [comment]
Done.

**Comment by vlad902** [comment]
Good god, what in git rebase did I do to this branch.

**Pull request merged**
