### PR TITLE
Add CLI for extract_implications

### PR DESCRIPTION
**Pull request by Command-Master**
Adds a CLI to `lake exe extract_implications`

- [ ] depends on: #93

### CODE REVIEW

**Comment by Command-Master** [comment]
awaiting-review

**Comment by pitmonticone** [comment]
Please merge from `main` and the CI checks will pass.

**Comment by Command-Master** [comment]
awaiting-review

**Comment by Command-Master** [comment]
do-not-merge

**Comment by Command-Master** [comment]
This is now subsumed by #126

**Pull request closed without merging**
