### PR TITLE
State and prove Theorem 2.36

### PR DESCRIPTION
**Pull request by jscanvic**
* Add theorems `Finite.Equation28394_implies_Equation2` and `Equation28394_not_implies_Equation2` closing #125.
* Introduce Equation28394, a fixed version of Equation28393.

### CODE REVIEW

**Comment by Shreyas4991** [comment]
@jscanvic : since this is a draft PR, GitHub won't automatically show this, but an upstream PR might have introduced merge conflicts due to the notation change for Magma. Could you check if merging the main branch into your branch works?

**Comment by jscanvic** [comment]
@Shreyas4991 It appears to be working after changing the notation.

**Comment by Shreyas4991** [comment]
The PR is marked as a draft. The CI will automatically run when the PR is not a draft anymore.

**Comment by jscanvic** [comment]
awaiting-review

**Comment by jscanvic** [comment]
The two equations are indeed completely different. As far as I can tell, giving the new one a new number would simply require changing it in the blueprint `infinite_models.tex`.

**Comment by Shreyas4991** [comment]
Then this would be the path of least resistance. I would recommend it.

**Comment by jscanvic** [comment]
Alright! I've made the changes from `28393` to `28394`.

**Comment by teorth** [comment]
Actually the equation `x = (((y ◇ y) ◇ y) ◇ x) ◇ (y ◇ z)` is numbered 28770, and `x = (((x ◇ x) ◇ x) ◇ y) ◇ (x ◇ z)` is equation 28381.  The full list can be found at https://github.com/teorth/equational_theories/blob/main/data/eq_size5.txt .  Sorry for screwing up the numbering previously, but this should be the canonical numbering to use going forward.

**Comment by jscanvic** [comment]
My bad. I wasn't aware of the extended numbering. It should be good now!

**Comment by teorth** [comment]
Small blueprint issue - one of the references to 28393 in the blueprint now has to be renumbered.  Sorry, that should be the last thing and then we can merge!

**Comment by jscanvic** [comment]
Done!

**Pull request merged**
